config/routes.rb
Rails.application.routes.draw do
  resources :videos

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'videos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
	def next
		Video.where("id > ?", id).first
	end

	def prev
		Video.where("id < ?", id).last 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wisitia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
	    base_title = "Code 4"
	    if page_title.empty?
	      base_title
	    else
	      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      = full_title(yield(:title))
    = csrf_meta_tags 

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    
        
    %link{ href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet" }

       
  %body
    %nav
      %div{ class: "nav-wrapper green darken-2 " }
        = link_to 'Core 4',  root_path, class: "brand-logo" 
        
        %a{ href: "#", 'data-activates' => "mobile-demo", class: "button-collapse" } 
          %i.material-icons menu
        %ul{ class: "right hide-on-med-and-down" }
          %li
            %a{ href: root_path }
              %i.material-icons list       
          %li
            %a{ href: static_pages_about_path }
              %i.material-icons perm_identity
          %li
            %a{ href: static_pages_contact_path }
              %i.material-icons location_on
        %ul{ class: "side-nav", id: "mobile-demo" }
          %li
            %a{ href: root_path }
              %i.material-icons list       
          %li
            %a{ href: static_pages_about_path }
              %i.material-icons perm_identity
          %li
            %a{ href: static_pages_contact_path }
              %i.material-icons location_on
              
    %div{ class: "row" }
      %div{ class: "col m10 offset-m1"}
        = yield

    %script 
      $(".button-collapse").sideNav();

app/views/static_pages/about.html.haml
%h3 About Me 

%div{ class: "card z-depth-3" }
  %div{ class: "row card-content white-text" }
    %div{ class: "col m6" }
      %div{ class: "card-panel grey lighten-5 z-depth-1" }
        %div{ class: "row valign-wrapper" }
          %div{ class: "col m3" }
            = image_tag("final-fantasy.jpg", class: "circle responsive-img" )

          %div{ class: "col m9" }
            %span{ class: "black-text"}
              I don't know what to say, let the world tells you more... ;)
    %div{ class: "col m6" }
      %div{ class: "card-panel grey lighten-5 z-depth-1" }
        %div{ class: "row valign-wrapper" }
          %div{ class: "col m3" }
            = image_tag("final-fantasy.jpg", class: "circle responsive-img" )

          %div{ class: "col m9" }
            %span{ class: "black-text"}
              I don't know what to say, let the world tells you more... ;)}

app/views/static_pages/contact.html.haml
%h3 Contact

%div{ class: "card z-depth-3" }
  %div{ class: "row card-content"}
    %p Do you wanna talk? Find me on the map and we can have some drinks
    %br/
    
    %iframe( src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15715.685318942078!2d-69.34735089999998!3d10.0677719!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sve!4v1473185837989" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen )

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .input-field
    = f.text_field :wisitia, placeholder: "link", length: "10"
  .input-field
    = f.text_field :title, placeholder: "Title", length: '20'
  .input-field
    = f.text_area :description, placeholder: "Description", length: '800', class: "materialize-textarea"
  = f.submit "Submit", class: "waves-effect waves-light btn"
  = link_to 'Back', videos_path, class: "waves-effect waves-light btn", name: "action"

app/views/videos/edit.html.haml
%h1 Editing video

.card
  .card-content
    = render 'form' 

app/views/videos/index.html.haml
%p{ id: "notice" }= notice

%h1 Listing Videos

= link_to new_video_path, class: "btn-floating btn-large waves-effect waves-light red" do 
  %i.material-icons add

%ul{ class: "collapsible", 'data-collapsible' => 'accordion', remote: true }
  -@videos.each do |video|
    %li
      %div.collapsible-header
        %i.material-icons library_books
        = link_to video.title, video, id: "show"
        %span.right
          = link_to edit_video_path(video) do 
            %i.material-icons mode_edit
          = link_to video, method: :delete, data: { confirm: "Are you sure?" } do 
            %i.material-icons delete_forever

      %div{ class: "collapsible-body" }
        %p= video.description 

app/views/videos/new.html.haml
%h1 New video

.card
  .card-content
    = render 'form'

app/views/videos/show.html.haml
%p#notice= notice

%div{ class: "row" }
  %div{ class: "col m3" }
    %div{ class: "collection" }
      - @videos.each do |video|
        = link_to video.title, video, class: "collection-item"

  %div{ class: "col m9" }
    %div{ class: "card blue-grey darken-1" }
      %div{ class: "card-image" }
        %div{ id: "wistia_#{@video.wisitia}" }
      %div{ class: "card-content white-text" }
        %button{ class: "btn btn-primary", onclick: "setPlayerSpeed(0.75)"} 0.75x
        %button{ class: "btn btn-primary", onclick: "setPlayerSpeed(1)"} 1x
        %button{ class: "btn btn-primary", onclick: "setPlayerSpeed(1.25)"} 1.25x
        %button{ class: "btn btn-primary", onclick: "setPlayerSpeed(1.5)"} 1.5x
        %button{ class: "btn btn-primary", onclick: "setPlayerSpeed(2)"} 2x
        %br/
        %span{ class: "card-title" }= @video.title
        %p= @video.description 

      %div{ class: "card-action" }
        = link_to 'Previous', @prev_video if !@prev_video.nil?
        %span{ class: "right" }
          = link_to 'Next', @next_video if !@next_video.nil?

%script{ src: "//fast.wistia.com/assets/external/E-v1.js" }
%script
  wistiaEmbed = Wistia.embed("#{@video.wisitia}", { 
  videoQuality: "hd-only",
  videoFoam: true
  });

  function setPlayerSpeed(speed) { wistiaEmbed.playbackRate(speed);
  }